### ISSUE TITLE
Font loading is broken in Firefox

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#123]
![image](https://github.com/Volumetrics-io/MR.js/assets/6750584/aef9ac3f-8887-4344-9a07-b67b92de7b69)

Right is Chrome, left is Firefox.

```css
@font-face {
    font-family: 'Hepta Slab';
    src: url('./fonts/HeptaSlab.ttf') format('truetype');
    font-weight: 100 900;
}
```

```html
mr-text {
    margin: 20px;
    font-size: 36px;
    line-height: 200%;
    font-family: "Hepta Slab";
}
```
