### ISSUE TITLE
<mr-button> 2d DOM element is visible

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#226]
Is that required for interactivity?
It feels weird that the 2D DOM element is still floating on top of the 3D scene

[Screencast from 2024-01-11 16-04-40.webm](https://github.com/Volumetrics-io/mrjs/assets/6750584/50567aeb-fb51-4797-bb4c-28ad43633e0e)

**Comment by lobau** [comment]
nevermind, there was this custom CSS that was messing up the scene. Closing.

```css
mr-app * {
    visibility: visible;
    box-sizing: content-box;
}

mr-app>canvas {
    visibility: visible;
}
```
