### ISSUE TITLE
mr.js seems to ignore CSS selectors like `:last-child`

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#239]
in this example, I would expect the second button to have a blue background:

```html
<mr-div class="nav">
  <mr-button>First child</mr-button>
  <mr-button>Last child</mr-button>
</mr-div>
```

```css
.nav {
  display: flex;
  flex-direction: row;
  width: 100%;
  height: 72px;
}

.nav:last-child {
  background-color: blue;
}
```
