### ISSUE TITLE
Can't fix text size

### ISSUE THREAD

**Issue by lobau** [Volumetrics-io/mrjs#512]
[Screencast from 2024-03-18 17-32-45.webm](https://github.com/Volumetrics-io/mrjs/assets/6750584/f2e40898-151e-46d9-aa16-f059e87c7542)

This is the page code:

```html
<mr-app debug="true" camera="perspective">
        <mr-light color="hsl(340, 100%, 50%)" intensity="5" data-position="-0.3 0.5 0.2"></mr-light>
        <mr-light color="hsl(180, 100%, 50%)" intensity="2.5" data-position="0 -0.5 0.4"></mr-light>
        <mr-light color="hsl(40, 100%, 50%)" intensity="5" data-position="0.6 0.25 0.2"></mr-light>
        <mr-panel data-rotation="-5 15 5">
            <mr-text class="title">Generate Skybox</mr-text>
            <mr-text class="body">Generate Skybox</mr-text>
            <mr-div class="logo-container" data-rotation="5 -5 5">
                <mr-model id="logo" src="logo.glb" data-rotation="0 0 180"></mr-model>
            </mr-div>
        </mr-panel>
    </mr-app>
```

```css
mr-app {
    width: 100vw;
    height: 100vh;
    border-radius: unset;
    background-color: transparent;
    display: flex;
    align-items: center;
    justify-content: center;
}

mr-panel {
    width: 300px;
    height: 300px;
    display: flex;
    flex-flow: column nowrap;
    gap: 20px;
    align-items: center;
    justify-content: center;
}

#logo {
    width: 300px;
    height: 300px;
    z-index: 100;
    scale: 1;
}

.logo-container {
    width: 100px;
    height: 100px;
}

.title {
    font-size: 40px;
}

.body {
    font-size: 20px;
}
```

I believe `mr-panel` behaves correctly (it's size is hardcoded to 300px width and 300px height), but `mr-title` is not.
The text size changes as I make the window taller, even though it's defined in px, just like mr-panel.
